#######################################################
# Local services for RCR
#######################################################

version: '3.5'
services:
  #######################################################
  # Postgres
  #######################################################
  postgresdb:
    image: postgres:alpine
    ports:
    - "5432:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data
    networks:
    - local_services
    environment:
      POSTGRES_USER: rcr_owner
      POSTGRES_PASSWORD: rcr_owner
      POSTGRES_DB: rcr_api
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s

  redis:
    image: redis:alpine
    ports:
    - "6379:6379"
    networks:
    - local_services
    volumes:
    - redisdata:/data
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s

volumes:
  pgdata:
  redisdata:

networks:
  local_services:
