version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 5
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 8
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: 50
  identical-code:
    enabled: true
plugins:
  sonar-java:
    enabled: true
    config:
      sonar.java.source: 8
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - TODO
      - BUG
exclude_patterns:
- ".mvn/"
- "launches/"
- "log/"
- "src/test/"
- "src/main/resources/"
- "mvnw"
- "mvnw.cmd"
