language: java
dist: xenial
sudo: false
cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.sonar/cache"
jobs:
  include:
    - stage: test
      script:
        - "./mvnw -B verify sonar:sonar"
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "defra"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - JACOCO_SOURCE_PATH=src/main/java ./cc-test-reporter format-coverage target/site/jacoco/jacoco.xml --input-type jacoco
  - ./cc-test-reporter upload-coverage
