###############################################################################
#
# Rod Catch Returns API Configuration Settings
#
# This file is split into different sections, the first provides defaults
# for all environments.  Subsequent sections provide profile-specific
# configurations which may be enabled to override the default values.
#
###############################################################################
spring:
  application:
    name: Data Returns Rod Catch Returns API
  datasource:
    url: jdbc:postgresql://localhost:5432/rcr_api
    username: rcr_owner
    password: rcr_owner
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect

# Configuration for the web server
server:
  display-name: rcr_api
  port: 9580

dynamics:
  impl: mock
  endpoint:
  api:

active-directory:
  tenant:
  authority:
  clientId:
  clientSecret:
  identityClientId:

validation:
  # Enable/disable all validation functionality
  enabled: true
  # Allow the current year and the previous (-1)
  submission-year-allowed-range-offset: -1

logging:
  level:
    com.microsoft.aad.adal4j: off


---
###############################################################################
#
# Profile: h2
#
###############################################################################
spring:
  profiles: h2
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

# Enable liquibase migrations when running in-memory
liquibase:
  enabled: true

---
###############################################################################
#
# Profile: CRM test data
#
###############################################################################
spring:
  profiles: crm-test-data
  profiles.include:
      - h2

test-data:
  licence:
    licence-number: D9D80E
    postcode: ST15 0LE
---