###############################################################################
#
# Rod Catch Returns API Configuration Settings
#
# This file is split into different sections, the first provides defaults
# for all environments.  Subsequent sections provide profile-specific
# configurations which may be enabled to override the default values.
#
###############################################################################
spring:
  application:
    name: Rod Catch Returns API
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/rcr_api
    username: rcr_owner
    password: rcr_owner
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect

# Configuration for the web server
server:
  servlet:
    application-display-name: rcr_api
  port: 9580

dynamics:
  impl: mock
  endpoint:
    url: http://mock-dynamics.example.com/
    api-path: api/data/v9.0

active-directory:
  authority: http://mock-ad.example.com/
  identity-client-id: example

cache:
  active-directory-cache-manager-ttl-hours: 24
  licence-cache-manager-ttl-hours: 24

security:
  oauth2:
    client:
      id: dynamics
      client-id:
      client-secret:
      scope:
      client-authentication-scheme: form
      grant-type: client_credentials

  role-authorities:
    RcrAdminUser:
      - USE_INTERNAL
      - REFERENCE_DATA_WRITE
    RcrFMTUser:
      - USE_INTERNAL
    RCR_END_USER:

logging:
  level:
    # Exceptions/errors are converted to spring exceptions as req'd - don't let the adal4j library log anything.
    com.microsoft.aad.adal4j: off
---
