###############################################################################
#
# Rod Catch Returns API Configuration Settings
#
# This file is split into different sections, the first provides defaults
# for all environments.  Subsequent sections provide profile-specific
# configurations which may be enabled to override the default values.
#
###############################################################################
spring:
  application:
    name: Data Returns Rod Catch Returns API
  datasource:
    url: jdbc:postgresql://localhost:5432/rcr_api
    username: rcr_owner
    password: rcr_owner
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect

# Configuration for the web server
server:
  display-name: rcr_api
  port: 9580

dynamics:
  impl: dynamics
  endpoint: https://ea-fish-devsandbox.crm4.dynamics.com
  api: api/data/v9.0

active-directory:
  tenant: Defra.onmicrosoft.com
  authority: https://login.microsoftonline.com
  clientId: b519a923-5721-43d5-80c5-8fadf91e6d98
  clientSecret: fPhRt1Z670y3U7OsDryOuhqqNWd+FcaDim44n51B74w=

---
###############################################################################
#
# Profile: h2
#
###############################################################################
spring:
  profiles: h2
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

# Enable liquibase migrations when running in-memory
liquibase:
  enabled: true
