###############################################################################
#
# Rod Catch Returns API Configuration Settings
#
# This file is split into different sections, the first provides defaults
# for all environments.  Subsequent sections provide profile-specific
# configurations which may be enabled to override the default values.
#
###############################################################################
spring:
  application:
    name: Data Returns Rod Catch Returns API
  datasource:
    url: jdbc:postgresql://localhost:5432/rcr_api
    username: rcr_owner
    password: rcr_owner
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect

# Configuration for the web server
server:
  display-name: rcr_api
  port: 9580

dynamics:
  impl: mock

active-directory:
  tenant:
  authority:
  client-id:
  client-secret:
  identity-client-id:

cache:
  active-directory-cache-manager-ttl-hours: 24
  licence-cache-manager-ttl-hours: 24

validation:
  # Enable/disable all validation functionality
  enabled: true
  # Allow the current year and the previous (-1)
  submission-year-allowed-range-offset: -1

security:
  role-authorities:
    RcrAdminUser:
    - JPA_ENTITY_DEFAULT_READ
    - JPA_ENTITY_DEFAULT_WRITE
    - JPA_ENTITY_DEFAULT_SUPER
    RcrFMTUser:
    - JPA_ENTITY_DEFAULT_READ
    - JPA_ENTITY_DEFAULT_SUPER
    - RIVER_WRITE
    RCR_END_USER:
    - JPA_ENTITY_DEFAULT_READ
---
